# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model_conf.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='model_conf.proto',
  package='model',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10model_conf.proto\x12\x05model\"&\n\rStickbandConf\x12\n\n\x02\x66\x64\x18\x01 \x01(\x01\x12\t\n\x01J\x18\x02 \x01(\x01\"(\n\x0c\x44\x65\x61\x64zoneConf\x12\x0b\n\x03\x63_l\x18\x01 \x01(\x01\x12\x0b\n\x03\x63_r\x18\x02 \x01(\x01\"(\n\x0c\x44\x65\x61\x64\x62\x61ndConf\x12\x0b\n\x03\x64_l\x18\x01 \x01(\x01\x12\x0b\n\x03\x64_r\x18\x02 \x01(\x01\"V\n\x1d\x46irstOrderInertialElementConf\x12\t\n\x01k\x18\x01 \x01(\x01\x12\x0b\n\x03tau\x18\x02 \x01(\x01\x12\x12\n\ninit_value\x18\x03 \x01(\x01\x12\t\n\x01N\x18\x04 \x01(\x01'
)




_STICKBANDCONF = _descriptor.Descriptor(
  name='StickbandConf',
  full_name='model.StickbandConf',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='fd', full_name='model.StickbandConf.fd', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='J', full_name='model.StickbandConf.J', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=65,
)


_DEADZONECONF = _descriptor.Descriptor(
  name='DeadzoneConf',
  full_name='model.DeadzoneConf',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='c_l', full_name='model.DeadzoneConf.c_l', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='c_r', full_name='model.DeadzoneConf.c_r', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=107,
)


_DEADBANDCONF = _descriptor.Descriptor(
  name='DeadbandConf',
  full_name='model.DeadbandConf',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='d_l', full_name='model.DeadbandConf.d_l', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='d_r', full_name='model.DeadbandConf.d_r', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=149,
)


_FIRSTORDERINERTIALELEMENTCONF = _descriptor.Descriptor(
  name='FirstOrderInertialElementConf',
  full_name='model.FirstOrderInertialElementConf',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='k', full_name='model.FirstOrderInertialElementConf.k', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tau', full_name='model.FirstOrderInertialElementConf.tau', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='init_value', full_name='model.FirstOrderInertialElementConf.init_value', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='N', full_name='model.FirstOrderInertialElementConf.N', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=237,
)

DESCRIPTOR.message_types_by_name['StickbandConf'] = _STICKBANDCONF
DESCRIPTOR.message_types_by_name['DeadzoneConf'] = _DEADZONECONF
DESCRIPTOR.message_types_by_name['DeadbandConf'] = _DEADBANDCONF
DESCRIPTOR.message_types_by_name['FirstOrderInertialElementConf'] = _FIRSTORDERINERTIALELEMENTCONF
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StickbandConf = _reflection.GeneratedProtocolMessageType('StickbandConf', (_message.Message,), {
  'DESCRIPTOR' : _STICKBANDCONF,
  '__module__' : 'model_conf_pb2'
  # @@protoc_insertion_point(class_scope:model.StickbandConf)
  })
_sym_db.RegisterMessage(StickbandConf)

DeadzoneConf = _reflection.GeneratedProtocolMessageType('DeadzoneConf', (_message.Message,), {
  'DESCRIPTOR' : _DEADZONECONF,
  '__module__' : 'model_conf_pb2'
  # @@protoc_insertion_point(class_scope:model.DeadzoneConf)
  })
_sym_db.RegisterMessage(DeadzoneConf)

DeadbandConf = _reflection.GeneratedProtocolMessageType('DeadbandConf', (_message.Message,), {
  'DESCRIPTOR' : _DEADBANDCONF,
  '__module__' : 'model_conf_pb2'
  # @@protoc_insertion_point(class_scope:model.DeadbandConf)
  })
_sym_db.RegisterMessage(DeadbandConf)

FirstOrderInertialElementConf = _reflection.GeneratedProtocolMessageType('FirstOrderInertialElementConf', (_message.Message,), {
  'DESCRIPTOR' : _FIRSTORDERINERTIALELEMENTCONF,
  '__module__' : 'model_conf_pb2'
  # @@protoc_insertion_point(class_scope:model.FirstOrderInertialElementConf)
  })
_sym_db.RegisterMessage(FirstOrderInertialElementConf)


# @@protoc_insertion_point(module_scope)
